#!/bin/bash
#väljastab kuu nimetuse vastavalt numbrile (1 jaanuar jne)

read -p "Sisestage kuu number: " sisend			#võtan kasutajalt inputi
case $sisend in						#kontrollin kas kastuaja input on mõni kuu number, kui ei ole saab ka vastava vastuse
	"1") echo "See on jaanuar";;
	"2") echo "See on veebruar";;
	"3") echo "See on märts";;
	"4") echo "See on aprill";;
	"5") echo "See on mai";;
	"6") echo "See on juuni";;
	"7") echo "See on juuli";;
	"8") echo "See on august";;
	"9") echo "See on september";;
	"10") echo "See on oktoober";;
	"11") echo "See on november";;
	"12") echo "See on detsember";;
	*) echo "u wot m8? insert a proper number you knob"
esac							#lõpetab case loopi
#skripti lõpp
