#!/bin/bash
#progamm väljastab
#1.*****
#2.*****
#3.*****
#4.*****
#5.*****


for (( i = 1 ; i<= 5; i++))		#mitu rida peab  tegema
do
echo -n "$i."				#rea number
	for (( j = 1 ; j <= 5; j++ ))	#mitu asja peab olema, preagu 5
	do
		echo -n "*"		#Mida iganes tahad ühes reas printida
	done
echo ""					#uus rida
done					#skripti lõpp
