#! /bin/bash
#
# Read tärnidega ja samal ajal väheneveb tärnide arv 
read -p "Sisesta ridade arv "  rida
for (( i = 1; i <= rida; i++ )) #reade tsükkel
do
	echo -n "$i."			#rea number
	for (( j = rida; j >= 1 ; j-- )) #Tulpade tsükkel
	do
		if [ $i -ge $j ]	#kursor, ehk kui rea arv on suurem kui tulba number siis on *
		then
			echo -n "* "
		else			#kui ei ole siis 0
			echo -n "0 "
		fi
	done
echo ""					#uus rida
done					#skripti lõpp
